export const theme = {
    colors: {
        primary: '#007AFF',
        secondary: '#6C757D',
        success: '#28A745', // For prices
        gray: '#6C757D',
        grayLight: '#EFEFEFFF',
        white: '#FFFFFF',
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 40,
        xxxl: 48,
        xxxxl: 56,
        xxxxxl: 64,
        xxxxxxl: 72,
        xxxxxxxl: 80,
        xxxxxxxxl: 88,
        xxxxxxxxxl: 96,
        xxxxxxxxxxl: 104,
        xxxxxxxxxxxl: 112,
        xxxxxxxxxxxxl: 120,
        xxxxxxxxxxxxxl: 128,
        xxxxxxxxxxxxxxl: 136,
        xxxxxxxxxxxxxxxl: 144,
    },
};